# Paths
SEMANTIC_MAPS_FOLDER_PATH = "data/semantic_maps/"
RESULTS_FOLDER_PATH = "results/"
CLUSTERINGS_FOLDER_PATH = "data/clusterings/"

# Semantic descriptors
SEMANTIC_DESCRIPTOR_NONE = "none"
SEMANTIC_DESCRIPTOR_BERT = "bert"
SEMANTIC_DESCRIPTOR_OPENAI = "openai"
SEMANTIC_DESCRIPTOR_ROBERTA = "roberta"
SEMANTIC_DESCRIPTOR_DEEPSEEK_SBERT = "deepseek+sbert"
SEMANTIC_DESCRIPTOR_DEEPSEEK_OPENAI = "deepseek+openai"
